In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import numpy as np
import time
from tqdm import tqdm
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt

# 1. Dataset Preprocessing
transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
])

train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True, num_workers=4, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=4, pin_memory=True)


100%|██████████| 170498071/170498071 [00:01<00:00, 96295425.58it/s] 


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [6]:
class ViT(nn.Module):
    def __init__(self, img_size=32, patch_size=4, num_classes=10, dim=64, depth=6, heads=8, mlp_dim=128):
        super(ViT, self).__init__()
        assert img_size % patch_size == 0, "Image dimensions must be divisible by the patch size."
        self.num_patches = (img_size // patch_size) ** 2
        self.patch_dim = 3 * patch_size ** 2

        self.patch_embeddings = nn.Linear(self.patch_dim, dim)
        self.position_embeddings = nn.Parameter(torch.randn(1, self.num_patches + 1, dim))
        self.cls_token = nn.Parameter(torch.randn(1, 1, dim))
        
        # Define the encoder layers
        encoder_layer = nn.TransformerEncoderLayer(d_model=dim, nhead=heads, dim_feedforward=mlp_dim, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=depth)
        
        self.to_cls_token = nn.Identity()
        self.mlp_head = nn.Sequential(
            nn.LayerNorm(dim),
            nn.Linear(dim, num_classes)
        )

    def forward(self, x):
        b, c, h, w = x.shape
        patch_size = int((h * w) // self.num_patches)
        x = x.unfold(2, patch_size, patch_size).unfold(3, patch_size, patch_size)
        x = x.contiguous().view(b, -1, self.patch_dim)  # Shape: [batch_size, num_patches, patch_dim]
        
        x = self.patch_embeddings(x)  # Apply patch embedding to get [batch_size, num_patches, dim]

        cls_tokens = self.cls_token.expand(b, -1, -1)  # Shape: [batch_size, 1, dim]
        x = torch.cat((cls_tokens, x), dim=1)  # Concatenate class token
        x += self.position_embeddings

        x = self.transformer_encoder(x)  # Pass through the encoder
        x = self.to_cls_token(x[:, 0])
        return self.mlp_head(x)


In [7]:
# 3. Model Training and Checkpointing
def train_model(model, train_loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    start_time = time.time()
    
    for images, labels in tqdm(train_loader):
        images, labels = images.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()

    training_time = time.time() - start_time
    avg_loss = running_loss / len(train_loader)
    
    return avg_loss, training_time

# 4. Evaluation and Metrics Logging
def evaluate_model(model, test_loader, device):
    model.eval()
    all_preds = []
    all_labels = []
    
    with torch.no_grad():
        for images, labels in tqdm(test_loader):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    accuracy = accuracy_score(all_labels, all_preds)
    precision = precision_score(all_labels, all_preds, average='weighted')
    recall = recall_score(all_labels, all_preds, average='weighted')
    f1 = f1_score(all_labels, all_preds, average='weighted')
    cm = confusion_matrix(all_labels, all_preds)

    return accuracy, precision, recall, f1, cm

# 5. Training Loop with Checkpointing and Logging
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ViT().to(device)
model = nn.DataParallel(model)  # Enable multi-GPU support
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

num_epochs = 20
best_f1 = 0.0
train_losses = []
val_accuracies = []

for epoch in range(num_epochs):
    train_loss, training_time = train_model(model, train_loader, criterion, optimizer, device)
    accuracy, precision, recall, f1, cm = evaluate_model(model, test_loader, device)
    
    train_losses.append(train_loss)
    val_accuracies.append(accuracy)
    
    # Save model at each epoch, overwriting the previous checkpoint
    torch.save(model, './model_checkpoint.pth')  # Save the entire model
    
    # Update best F1 score for reference (if needed)
    if f1 > best_f1:
        best_f1 = f1
    
    # Log metrics to file
    with open('metrics_log.txt', 'a') as f:
        f.write(f'Epoch: {epoch+1}, Loss: {train_loss}, Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Time: {training_time}\n')

    print(f'Epoch {epoch+1}/{num_epochs} - Loss: {train_loss:.4f} - Accuracy: {accuracy:.4f} - F1-score: {f1:.4f}')
    print(f'Confusion Matrix:\n{cm}')


# 6. Plotting Training and Validation Curves
plt.figure(figsize=(12, 5))

# Plot Loss Curve
plt.subplot(1, 2, 1)
plt.plot(range(1, num_epochs + 1), train_losses, label='Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training Loss Curve')
plt.legend()

# Plot Accuracy Curve
plt.subplot(1, 2, 2)
plt.plot(range(1, num_epochs + 1), val_accuracies, label='Validation Accuracy', color='orange')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Validation Accuracy Curve')
plt.legend()

plt.tight_layout()
plt.savefig('training_validation_curves.png')
plt.show()


100%|██████████| 79/79 [00:02<00:00, 32.42it/s]


Epoch 1/10 - Loss: 2.1641 - Accuracy: 0.2753 - F1-score: 0.2542
Confusion Matrix:
[[300  41  41  20  22 125  40  14 339  58]
 [ 42 255  13  55  30 150  77  40 173 165]
 [ 72  36 114  29 127 231 260  23  74  34]
 [ 38  68  39  68  75 355 230  39  38  50]
 [ 25  32  70  30 172 185 364  34  60  28]
 [ 34  46  49  54  52 477 178  31  43  36]
 [ 17  31  52  31 121 207 452  27  26  36]
 [ 27  64  32  43  73 265 183  63  79 171]
 [139  69  23  11  24 111  16   9 497 101]
 [ 41 116  13  36  22 107  66  38 206 355]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.25it/s]


Epoch 2/10 - Loss: 1.9332 - Accuracy: 0.3269 - F1-score: 0.3108
Confusion Matrix:
[[411  43  66   7  27  58  19  13 300  56]
 [ 61 298  22  32  27  71  50  41 214 184]
 [109  45 226  31 149 159 181  18  49  33]
 [ 52  57 130  72  83 328 136  60  28  54]
 [ 45  26 190  29 312  78 201  40  52  27]
 [ 45  30 102  48  76 463 130  47  36  23]
 [ 16  26 139  29 139 137 414  52  16  32]
 [ 42  69 101  36 113 192 100 128  57 162]
 [158  72  29  10  23  43   8   7 569  81]
 [ 59 122  22  18  32  61  47  56 207 376]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.19it/s]


Epoch 3/10 - Loss: 1.8479 - Accuracy: 0.3442 - F1-score: 0.3265
Confusion Matrix:
[[260  51  29  49  34  90  27  25 324 111]
 [ 13 411   4  28  11  83  40  67 113 230]
 [ 57  38 111  42 175 224 204  66  43  40]
 [ 13  61  45  78  62 403 161  98  21  58]
 [ 19  32  78  23 293 135 257  79  43  41]
 [  4  36  39  39  39 565 131  94  24  29]
 [  4  38  45  40  96 170 471  96   6  34]
 [  9  71  18  41  85 216 113 274  22 151]
 [ 65 121   4  22  19  64  13  24 538 130]
 [ 12 178   6  23  11  79  37  97 116 441]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
  0%|          | 0/79 [00:00<?, ?it/s]Exception in thread Thread-3620 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

    self.run()
  File "/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data

KeyboardInterrupt: 

# Fine-tuning for additional epochs using LR scheduler

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau

# Define device (ensure it uses only one GPU)
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

# Load the entire model as it was saved
model_path = '/kaggle/working/model_checkpoint.pth'
model = torch.load(model_path, map_location=device)  # Load full model directly
model = model.to(device)

# Define optimizer and scheduler
optimizer = optim.Adam(model.parameters(), lr=1e-4)
scheduler = ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=3, verbose=True)

# Training loop as before
num_epochs = 20
best_f1 = 0.0
train_losses = []
val_accuracies = []

for epoch in range(num_epochs):
    # Training phase
    train_loss, training_time = train_model(model, train_loader, criterion, optimizer, device)
    accuracy, precision, recall, f1, cm = evaluate_model(model, test_loader, device)
    
    train_losses.append(train_loss)
    val_accuracies.append(accuracy)
    
    # Save the full model checkpoint for retraining or deployment
    if f1 > best_f1:
        best_f1 = f1
        torch.save(model, '/kaggle/working/data/full_model_checkpoint_2.pth')  # Save the full model
    
    # Step the scheduler based on validation accuracy
    scheduler.step(accuracy)
    
    # Log metrics to file
    with open('metrics_log_continued.txt', 'a') as f:
        f.write(f'Epoch: {epoch+1}, Loss: {train_loss}, Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}, Time: {training_time}\n')

    print(f'Epoch {epoch+1}/{num_epochs} - Loss: {train_loss:.4f} - Accuracy: {accuracy:.4f} - F1-score: {f1:.4f}')
    print(f'Confusion Matrix:\n{cm}')


/tmp/ipykernel_30/1750144328.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(model_path, map_location=device)  # Load full model directly
  7%|▋     

Epoch 1/20 - Loss: 1.7921 - Accuracy: 0.3635 - F1-score: 0.3487
Confusion Matrix:
[[421  76  20  16  45  26  18  34 296  48]
 [ 41 528   1  22  15  12  20  57 155 149]
 [113  61 117  52 274  88 130  91  34  40]
 [ 55 106  35 129 106 211 108 155  32  63]
 [ 51  50  49  30 440  54 135 117  49  25]
 [ 41  60  37  92 109 346  90 141  43  41]
 [ 19  58  30  46 222  79 361 132  14  39]
 [ 40 113  22  48 128  84  53 338  50 124]
 [146 140   3  15  27  14   2  16 579  58]
 [ 43 260   4  20  14  21  17  79 166 376]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 27.75it/s]


Epoch 2/20 - Loss: 1.7587 - Accuracy: 0.3731 - F1-score: 0.3615
Confusion Matrix:
[[441  53  26  22  53  19  19  35 281  51]
 [ 43 442   3  27  20  24  32  47 204 158]
 [104  32 134  80 281  91 124  80  42  32]
 [ 55  55  38 162 118 231 127 113  44  57]
 [ 51  30  65  35 452  40 148 102  56  21]
 [ 31  27  50 144  98 367  91 115  50  27]
 [ 14  31  38  66 217  86 385 106  23  34]
 [ 36  72  38  69 133 110  58 357  42  85]
 [131  90   7  14  25  20   6  17 626  64]
 [ 48 212   5  27  22  21  30  84 186 365]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 31.93it/s]


Epoch 3/20 - Loss: 1.7268 - Accuracy: 0.3912 - F1-score: 0.3846
Confusion Matrix:
[[387  66  71  25  34  23  25  21 290  58]
 [ 27 505   7  26  19  29  33  40 161 153]
 [ 84  32 278  58 184 112 137  55  30  30]
 [ 28  43 104 173  82 255 135  88  28  64]
 [ 38  29 162  32 373  53 156  93  43  21]
 [ 18  31 105 113  70 414 105  79  34  31]
 [  7  36 128  47 149  86 433  67  12  35]
 [ 25  80  61  65 116 114  69 337  40  93]
 [103  99  23  18  21  23   8  14 628  63]
 [ 38 227  18  35  14  25  24  68 167 384]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.84it/s]


Epoch 4/20 - Loss: 1.6977 - Accuracy: 0.3900 - F1-score: 0.3792
Confusion Matrix:
[[384  52  98  17  26  21  31  24 286  61]
 [ 27 464  17  22  13  18  50  29 170 190]
 [ 79  32 347  34 112  95 196  43  33  29]
 [ 30  39 150  98  53 269 199  73  27  62]
 [ 39  23 246  21 274  51 217  64  41  24]
 [  6  27 153  59  51 423 155  67  32  27]
 [  9  27 163  26  69  66 556  33  14  37]
 [ 21  61 100  35  91 120 114 339  26  93]
 [115  94  23  14  16  24  14  14 617  69]
 [ 31 200  20  19  14  24  51  62 181 398]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:03<00:00, 25.93it/s]


Epoch 5/20 - Loss: 1.6752 - Accuracy: 0.4063 - F1-score: 0.3961
Confusion Matrix:
[[369  73  62  17  32  24  28  40 291  64]
 [ 17 536   5  31   7  11  28  55 140 170]
 [ 73  43 259  63 137  97 166  96  40  26]
 [ 21  67  71 147  57 253 162 133  25  64]
 [ 25  43 131  34 316  59 191 130  52  19]
 [ 15  43  72 106  57 421 108 121  32  25]
 [  6  34  97  45 118  63 499  95  19  24]
 [ 12  70  38  50  74 105  53 487  29  82]
 [ 77 119  12  14  11  29  11  20 632  75]
 [ 20 256   7  27  11   9  38  79 156 397]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.63it/s]


Epoch 6/20 - Loss: 1.6537 - Accuracy: 0.4164 - F1-score: 0.4095
Confusion Matrix:
[[451  55  47   9  39  22  23  25 257  72]
 [ 38 433  11  29  23  20  20  45 125 256]
 [ 98  16 249  48 221 115 100  84  35  34]
 [ 46  26  74 175  86 291 111  96  27  68]
 [ 51  15 115  51 400  57 138 110  36  27]
 [ 23  13  76 113  73 450  84 103  27  38]
 [ 13  13  89  55 169  82 450  75  14  40]
 [ 27  32  43  60 103 123  42 446  30  94]
 [104  87   7  16  19  23   9  15 616 104]
 [ 33 170  10  30  11  23  26  61 142 494]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 30.77it/s]


Epoch 7/20 - Loss: 1.6382 - Accuracy: 0.4221 - F1-score: 0.4165
Confusion Matrix:
[[498  71  59  15  28  19  30  23 195  62]
 [ 45 553   7  28   9  12  24  36 120 166]
 [ 95  25 294  80 132 115 145  64  24  26]
 [ 36  42  71 231  44 261 155  83  20  57]
 [ 53  24 173  50 285  57 196 104  35  23]
 [ 30  21  73 170  48 419 104  86  22  27]
 [ 10  28  99  90  94  65 520  56  11  27]
 [ 39  49  53  75  78 126  68 412  18  82]
 [148 102  11  25  10  25  10  17 585  67]
 [ 57 237  14  39   5  14  30  51 129 424]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 26.54it/s]


Epoch 8/20 - Loss: 1.6195 - Accuracy: 0.4273 - F1-score: 0.4198
Confusion Matrix:
[[480  68  49  20  25  11  31  21 252  43]
 [ 37 543  10  23  15   4  32  33 147 156]
 [ 85  36 247  81 189  76 163  71  27  25]
 [ 33  45  77 223  59 202 199  75  27  60]
 [ 48  27 131  49 385  37 175  93  39  16]
 [ 15  25  66 190  61 353 139  91  31  29]
 [  9  14  63  63 151  50 560  50  14  26]
 [ 36  65  22  86 107  77  77 433  24  73]
 [115  98   7  21  15  13  12  13 652  54]
 [ 43 243  12  36  12   5  38  58 156 397]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.20it/s]


Epoch 9/20 - Loss: 1.6087 - Accuracy: 0.4292 - F1-score: 0.4252
Confusion Matrix:
[[470  65  51  26  19  14  26  23 258  48]
 [ 29 512   6  39   9  13  13  26 152 201]
 [ 95  28 273 148 111 104 108  63  39  31]
 [ 45  36  66 341  40 233  82  55  26  76]
 [ 50  25 169 106 284  61 134 111  38  22]
 [ 20  15  60 244  38 416  64  69  35  39]
 [  9  25  79 154 112  87 432  44  19  39]
 [ 51  39  34 116  69 114  37 413  33  94]
 [ 97  85   4  20   6  22   9  14 688  55]
 [ 39 205   8  45   7  14  21  40 158 463]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.48it/s]


Epoch 10/20 - Loss: 1.5908 - Accuracy: 0.4379 - F1-score: 0.4315
Confusion Matrix:
[[475  62  59  27  22  12  34  13 213  83]
 [ 31 574   5  23  11   8  35  15 104 194]
 [ 91  19 255  99 130  95 205  50  26  30]
 [ 34  34  60 276  42 228 198  44  22  62]
 [ 54  18 144  63 305  44 237  70  39  26]
 [ 17  15  55 210  40 407 153  50  23  30]
 [ 10  18  68  85  66  56 624  25  15  33]
 [ 33  43  47  88  99 115  97 360  20  98]
 [110 105  17  25  15  14  12   6 614  82]
 [ 27 234   8  40   8  17  38  29 110 489]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 29.51it/s]


Epoch 11/20 - Loss: 1.5833 - Accuracy: 0.4356 - F1-score: 0.4286
Confusion Matrix:
[[458  52  59  23  25  30  38  29 229  57]
 [ 41 559   6  33   9  17  51  34 101 149]
 [ 78  31 266  95 108 107 209  56  26  24]
 [ 30  31  70 214  45 292 200  60  19  39]
 [ 35  19 151  56 307  55 239  90  37  11]
 [ 12  13  66 147  38 458 160  70  21  15]
 [  5  17  69  63  76  65 639  36  13  17]
 [ 27  35  36  78  78 138 115 426  12  55]
 [ 98 105  13  24  17  32  13  15 622  61]
 [ 33 255   8  37   7  26  56  61 110 407]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.00it/s]


Epoch 12/20 - Loss: 1.5713 - Accuracy: 0.4487 - F1-score: 0.4420
Confusion Matrix:
[[523  62  51   9  33  18  21  27 203  53]
 [ 46 612   7  13   8   7  18  40  79 170]
 [ 93  42 326  53 151  84  97  96  28  30]
 [ 50  36  93 204  67 227  95 123  18  87]
 [ 43  16 183  32 362  49 107 143  41  24]
 [ 18  26 108 118  52 401  81 128  32  36]
 [ 12  33 109  58 142  60 453  83   9  41]
 [ 44  43  45  50  82  76  43 517  18  82]
 [ 92 115  13  12  17  14  12  14 616  95]
 [ 33 262  20  13  10  15  14  63  97 473]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.92it/s]


Epoch 13/20 - Loss: 1.5566 - Accuracy: 0.4509 - F1-score: 0.4415
Confusion Matrix:
[[524  70  33  20  22  24  26  25 197  59]
 [ 39 623   6  18   9   8  13  28  87 169]
 [101  35 236  94 145 103 146  86  28  26]
 [ 50  49  73 237  40 246 138  78  22  67]
 [ 60  33 112  57 312  42 201 122  36  25]
 [ 24  26  50 145  33 453 117 100  22  30]
 [ 17  33  62  78  86  60 567  53   7  37]
 [ 43  52  32  60  63 111  50 496  16  77]
 [117 114   9  11  12  23   9   9 610  86]
 [ 39 280   8  30   7  11  20  42 112 451]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 29.53it/s]


Epoch 14/20 - Loss: 1.5515 - Accuracy: 0.4493 - F1-score: 0.4413
Confusion Matrix:
[[529  45  55  12  29  15  33  18 205  59]
 [ 43 543  12  27  11  11  28  29 119 177]
 [ 99  31 302  68 124  96 169  61  26  24]
 [ 53  25 100 215  40 253 200  47  15  52]
 [ 51  19 186  49 297  41 211  93  32  21]
 [ 23  11 102 138  36 442 119  70  28  31]
 [ 12  14  82  63  76  61 631  24  16  21]
 [ 52  33  50  64 112 100  82 409  24  74]
 [107  87  16  16  16  15  13  11 655  64]
 [ 40 212  13  29  12  11  42  41 130 470]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 31.92it/s]


Epoch 15/20 - Loss: 1.5405 - Accuracy: 0.4509 - F1-score: 0.4390
Confusion Matrix:
[[482  67  34  13  26  12  40  15 268  43]
 [ 32 591   2  18   7   9  26  15 148 152]
 [ 89  29 196  84 194  88 184  66  39  31]
 [ 39  46  41 223  64 223 205  72  26  61]
 [ 45  25  72  43 394  45 219  81  50  26]
 [ 23  21  47 169  49 405 158  65  33  30]
 [  9  22  34  60 109  43 637  39  20  27]
 [ 29  51  22  72  91  83  93 436  26  97]
 [ 76  93   3  17  10  16  11   6 704  64]
 [ 36 242   5  33   9  12  36  40 146 441]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.04it/s]


Epoch 16/20 - Loss: 1.5367 - Accuracy: 0.4535 - F1-score: 0.4465
Confusion Matrix:
[[484  65  45  43  22  22  32  22 189  76]
 [ 29 595   5  34   5   7  29  18  75 203]
 [ 83  35 228 152 115  87 193  53  29  25]
 [ 23  41  45 367  21 182 188  42  22  69]
 [ 49  34 112 105 285  41 248  70  37  19]
 [ 20  19  36 295  23 364 142  54  23  24]
 [  8  19  42 111  49  34 669  23  13  32]
 [ 26  55  28 122  72 112  76 395  14 100]
 [ 95  91   9  39  10  13  10  10 638  85]
 [ 25 241   5  40   6  11  32  27 103 510]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 31.21it/s]


Epoch 17/20 - Loss: 1.5225 - Accuracy: 0.4604 - F1-score: 0.4546
Confusion Matrix:
[[470  44  82  19  35  21  34  17 232  46]
 [ 37 548  10  22  13   7  34  17 128 184]
 [ 67  20 327  72 159  78 179  49  29  20]
 [ 26  24 101 215  72 236 208  39  19  60]
 [ 27  16 163  36 397  35 191  70  46  19]
 [ 15  14 101 138  63 415 144  64  23  23]
 [  2  20  80  60 112  38 632  20  15  21]
 [ 28  35  43  59 125 112  84 432  13  69]
 [ 74  73  17  18  25  15  12   9 696  61]
 [ 34 209  15  27  14  14  46  38 131 472]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 32.58it/s]


Epoch 18/20 - Loss: 1.5148 - Accuracy: 0.4626 - F1-score: 0.4576
Confusion Matrix:
[[485  39  79  10  41  22  30  36 211  47]
 [ 48 509  14  24  23  12  22  57  95 196]
 [ 65  16 365  57 146 103 127  73  29  19]
 [ 26  12 105 195  72 281 172  82  19  36]
 [ 37  11 195  29 380  52 146 104  34  12]
 [ 15  10 104 103  70 434 119 109  24  12]
 [  9   9 100  53 135  55 562  52   8  17]
 [ 23  19  47  44 115 102  52 543  11  44]
 [ 85  72  18  15  30  12  11  26 665  66]
 [ 37 160  11  32  21  19  43  81 108 488]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 33.15it/s]


Epoch 19/20 - Loss: 1.5062 - Accuracy: 0.4695 - F1-score: 0.4645
Confusion Matrix:
[[513  51  83  21  23  26  35  25 164  59]
 [ 54 584  13  23   8  11  29  19  66 193]
 [ 79  19 371  70 104 106 153  56  18  24]
 [ 27  26 109 254  31 284 159  61  12  37]
 [ 41  11 229  42 275  70 188 101  30  13]
 [ 11   9  94 157  34 479 111  72  15  18]
 [  3  13 106  59  65  56 656  16   9  17]
 [ 27  33  55  59  81 136  69 467   7  66]
 [112  90  21  17  19  28  14   9 607  83]
 [ 47 205  14  36   8  24  48  46  83 489]]


  0%|          | 0/391 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
100%|██████████| 79/79 [00:02<00:00, 30.59it/s]

Epoch 20/20 - Loss: 1.5004 - Accuracy: 0.4615 - F1-score: 0.4517
Confusion Matrix:
[[521  73  49  16  21  13  40   7 212  48]
 [ 20 652   8  25   4   3  42  12  82 152]
 [104  35 248  99 105  63 227  58  30  31]
 [ 37  37  50 300  28 173 243  41  32  59]
 [ 49  23 126  60 298  28 284  65  37  30]
 [ 27  13  66 218  34 348 172  62  27  33]
 [ 10  19  52  71  50  21 711  23  16  27]
 [ 37  48  24  93  88  79 106 415  26  84]
 [ 90  95   5  17  14   7  19   5 672  76]
 [ 37 278   5  36   6  10  52  25 101 450]]
